### ISSUE TITLE
Parenthesis not showing, they make text italics

### ISSUE THREAD

**Issue by MauroCE** [widgetfactory/wf-mathjax#1]
I am creating a [website][1] on Joomla, I am using HTML to write an article. Because I needed to write Maths stuff, I googled a little bit how to use LaTex on HTML. I encountered this: https://github.com/widgetfactory/wf-mathjax

Which is a Joomla extension (written in PHP). I've installed it and then tried using standard mathematics stuff, such as $a = b + c$ and it worked! The issue though, is that now if I just type 

    <p>This text is (in parenthesis) but it doesn't work. </p>

Then instead of having "This text is in (parenthesis) but it doesn't work", I get:

"This text is *in parenthesis* but it doesn't work."

**How to reproduce my error:**

If you follow the link to my website, after the main image you'll see:

[![mathjax][2]][2]

where my HTML code is:

    <h1>Header 1</h1>
    <h2>Header 2</h2>
    <p>This text uses normal (parenthesis)</p>
    <p>This text uses ASCII &#40; parenthesis &#x29;. </p>
    <p>This is a list of stuff in parethesis (one two three four) and it doesn't work.</p>
    <p> This is some inline math $a = b+c$</p>

  [1]: http://simpleai.it/it/style-your-website.html
  [2]: https://i.stack.imgur.com/GjEaM.png

**Comment by ryandemmer** [comment]
I have updated the plugin to remove ( ) as an inline delimiter, and allow you to set custom delimiters.

The default inline delimiter is now $ $. You can change this in the plugin parameters.

**Comment by MauroCE** [comment]
It works perfectly now, thanks!
